/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppBookRouteImport } from './routes/_app/book'
import { Route as AppDeskRouteImport } from './routes/_app/desk'
import { Route as AppHistoryRouteImport } from './routes/_app/history'
import { Route as SShareIdRouteImport } from './routes/s.$shareId'
import { Route as AppBookTicketIdRouteImport } from './routes/_app/book.$ticketId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiEspnGameRouteImport } from './routes/api/espn/game'
import { Route as ApiEspnSlateRouteImport } from './routes/api/espn/slate'
import { Route as AppWatchLeagueIdEventIdRouteImport } from './routes/_app/watch.$leagueId.$eventId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppBookRoute = AppBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => AppRoute,
} as any)
const AppDeskRoute = AppDeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const SShareIdRoute = SShareIdRouteImport.update({
  id: '/s/$shareId',
  path: '/s/$shareId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBookTicketIdRoute = AppBookTicketIdRouteImport.update({
  id: '/$ticketId',
  path: '/$ticketId',
  getParentRoute: () => AppBookRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEspnGameRoute = ApiEspnGameRouteImport.update({
  id: '/api/espn/game',
  path: '/api/espn/game',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEspnSlateRoute = ApiEspnSlateRouteImport.update({
  id: '/api/espn/slate',
  path: '/api/espn/slate',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWatchLeagueIdEventIdRoute = AppWatchLeagueIdEventIdRouteImport.update({
  id: '/watch/$leagueId/$eventId',
  path: '/watch/$leagueId/$eventId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/book': typeof AppBookRouteWithChildren
  '/desk': typeof AppDeskRoute
  '/history': typeof AppHistoryRoute
  '/s/$shareId': typeof SShareIdRoute
  '/book/$ticketId': typeof AppBookTicketIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/espn/game': typeof ApiEspnGameRoute
  '/api/espn/slate': typeof ApiEspnSlateRoute
  '/watch/$leagueId/$eventId': typeof AppWatchLeagueIdEventIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/book': typeof AppBookRouteWithChildren
  '/desk': typeof AppDeskRoute
  '/history': typeof AppHistoryRoute
  '/s/$shareId': typeof SShareIdRoute
  '/': typeof AppIndexRoute
  '/book/$ticketId': typeof AppBookTicketIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/espn/game': typeof ApiEspnGameRoute
  '/api/espn/slate': typeof ApiEspnSlateRoute
  '/watch/$leagueId/$eventId': typeof AppWatchLeagueIdEventIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_app/book': typeof AppBookRouteWithChildren
  '/_app/desk': typeof AppDeskRoute
  '/_app/history': typeof AppHistoryRoute
  '/s/$shareId': typeof SShareIdRoute
  '/_app/': typeof AppIndexRoute
  '/_app/book/$ticketId': typeof AppBookTicketIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/espn/game': typeof ApiEspnGameRoute
  '/api/espn/slate': typeof ApiEspnSlateRoute
  '/_app/watch/$leagueId/$eventId': typeof AppWatchLeagueIdEventIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/book'
    | '/desk'
    | '/history'
    | '/s/$shareId'
    | '/book/$ticketId'
    | '/api/auth/$'
    | '/api/espn/game'
    | '/api/espn/slate'
    | '/watch/$leagueId/$eventId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/book'
    | '/desk'
    | '/history'
    | '/s/$shareId'
    | '/'
    | '/book/$ticketId'
    | '/api/auth/$'
    | '/api/espn/game'
    | '/api/espn/slate'
    | '/watch/$leagueId/$eventId'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/signup'
    | '/_app/book'
    | '/_app/desk'
    | '/_app/history'
    | '/s/$shareId'
    | '/_app/'
    | '/_app/book/$ticketId'
    | '/api/auth/$'
    | '/api/espn/game'
    | '/api/espn/slate'
    | '/_app/watch/$leagueId/$eventId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  SShareIdRoute: typeof SShareIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiEspnGameRoute: typeof ApiEspnGameRoute
  ApiEspnSlateRoute: typeof ApiEspnSlateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/book': {
      id: '/_app/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof AppBookRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/desk': {
      id: '/_app/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof AppDeskRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/s/$shareId': {
      id: '/s/$shareId'
      path: '/s/$shareId'
      fullPath: '/s/$shareId'
      preLoaderRoute: typeof SShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/book/$ticketId': {
      id: '/_app/book/$ticketId'
      path: '/$ticketId'
      fullPath: '/book/$ticketId'
      preLoaderRoute: typeof AppBookTicketIdRouteImport
      parentRoute: typeof AppBookRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/espn/game': {
      id: '/api/espn/game'
      path: '/api/espn/game'
      fullPath: '/api/espn/game'
      preLoaderRoute: typeof ApiEspnGameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/espn/slate': {
      id: '/api/espn/slate'
      path: '/api/espn/slate'
      fullPath: '/api/espn/slate'
      preLoaderRoute: typeof ApiEspnSlateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/watch/$leagueId/$eventId': {
      id: '/_app/watch/$leagueId/$eventId'
      path: '/watch/$leagueId/$eventId'
      fullPath: '/watch/$leagueId/$eventId'
      preLoaderRoute: typeof AppWatchLeagueIdEventIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppBookRouteChildren {
  AppBookTicketIdRoute: typeof AppBookTicketIdRoute
}

const AppBookRouteChildren: AppBookRouteChildren = {
  AppBookTicketIdRoute: AppBookTicketIdRoute,
}

const AppBookRouteWithChildren =
  AppBookRoute._addFileChildren(AppBookRouteChildren)

interface AppRouteChildren {
  AppBookRoute: typeof AppBookRouteWithChildren
  AppDeskRoute: typeof AppDeskRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppIndexRoute: typeof AppIndexRoute
  AppWatchLeagueIdEventIdRoute: typeof AppWatchLeagueIdEventIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBookRoute: AppBookRouteWithChildren,
  AppDeskRoute: AppDeskRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppIndexRoute: AppIndexRoute,
  AppWatchLeagueIdEventIdRoute: AppWatchLeagueIdEventIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  SShareIdRoute: SShareIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiEspnGameRoute: ApiEspnGameRoute,
  ApiEspnSlateRoute: ApiEspnSlateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
